### ISSUE TITLE
Change resolution

### ISSUE THREAD

**Issue by jprehbein** [xuzhizun/ids_peak_cam#1]
Hello,
Thank you for your package, it worked flawlessly for me but I was wondering if there is any way to change the resolution of the image received in the `/.../image_raw` topic. So far I only receive it in black and white and with some grid imprinted. Does that occur because of some filtering or compressing?
I would consider myself a beginner so I would be very thankful for any kind of help.

**Comment by xuzhizun** [comment]
hello,

so far, the ros driver is written for ids monochrome camera (grayscale cam).

 Since the structure of colour cam's data streaming  is different with mono-cam, it is reasonable to find some distortion on your images if you using ids colour cam. 

To apply the driver for colour cams, you have to make slight modification on the code. 

In src/ids_peak_cam.cpp, from 183 to 190 lines, changing following codes,

` image.encoding = sensor_msgs::image_encodings::MONO8;
`
to

` image.encoding = sensor_msgs::image_encodings::RGB8;
`
I didn't test, but expected to work, if your image is 8bits.

For the resolution, the driver can detect the your cam resolution automatically.

**Comment by jprehbein** [comment]
Hello,
Thank you for your quick response. That was also what i tried first after looking into the source code, with no luck. The image_raw topic is being published to when I change the encoder, but rviz gives me an error when I try to inspect it. It gives me an OGRE exception like so:

`Error loading image: OGRE EXCEPTION(2:InvalidParametersException): Stream size does not match calculated image size in Image::loadRawData`

This is usually an error when the wrong encoder is chosen but I checked RBG8 and BGR8, both are supported by my camera when I use the official IDS software. Do you have anything in mind that could help with that?
Thank you again for all your help so far.

**Comment by xuzhizun** [comment]
Hello,

The error means the size of steam from you device is different with that of image created by using OpenCV.

You need set up image step, because the grayscale image is only one channel, but the RGB8 is three channel.

so,  from line  179-187 in src/ids_peak_cam.cpp, changing following 
```
   image.height = dev_image.Height();
   image.width = dev_image.Width();
   image.step = dev_image.Width();

   image.encoding = sensor_msgs::image_encodings::MONO8;

   int image_size =dev_image.Height()*dev_image.Width(); 

   int sizeBuffer = static_cast<int>(dev_image.ByteCount());

   image.data.resize(dev_image.Height()*dev_image.Width());
```
to
```
   image.height = dev_image.Height();
   image.width = dev_image.Width();
   image.encoding = sensor_msgs::image_encodings::RGB8;
  
 image.step = image.width * static_cast<unsigned int>(sensor_msgs::image_encodings::numChannels(image.encoding)) * static_cast<unsigned int>(sensor_msgs::image_encodings::bitDepth(image.encoding))/8;
  
 int sizeBuffer = static_cast<int>(dev_image.ByteCount());
  
 image.data.resize(image.height * image.step);
```
  
It should work.

**Comment by jprehbein** [comment]
Thank you again for your quick help. Now I can use RGB8 as an encoder but in RVIZ the three channels are all depicted separately. Ill put a picture from the output below so its easier to see what I mean. Do these layers have to be put on each other? 
![rgb8_encoding](https://github.com/xuzhizun/ids_peak_cam/assets/59611184/b548450a-7e71-4732-801e-39210fdc8e80)

**Comment by xuzhizun** [comment]
It seems the format of stream is not RGB8. I am not sure about the default format of your cam. 

But I can convert it to RGB8 if you like,

From src/ids_peak_cam.cpp, changing 173 line 

`auto dev_image = peak::BufferTo<peak::ipl::Image>(buffer);`

to 

```
auto image_raw = peak::ipl::Image(peak::BufferTo<Image>(buffer));
auto dev_image = image_raw.ConvertTo(peak::ipl::PixelFormatName::RGB8, peak::ipl::ConversionMode::Fast);
```

and show me results.

**Comment by jprehbein** [comment]
Thank you very much, it runs completely fine now. Only thing, I think instead of 
`auto image_raw = peak::ipl::Image(peak::BufferTo<Image>(buffer));`
it is meant to be 
`auto image_raw = peak::ipl::Image(peak::BufferTo<peak::ipl::Image>(buffer));`
At least for me it didnt work before that change. Results are in the picture below again. Besides some strong blue tones it looks fine. Thank you for all your help. Do you also plan on implementing support for multiple cameras?
![rviz_test](https://github.com/xuzhizun/ids_peak_cam/assets/59611184/0f8c7c18-a4c2-447a-b3a8-3683c7918873)

**Comment by xuzhizun** [comment]
You need to process white balance to get real colour. 

Sorry, no plan for multi-cam yet.
